spring:
    application:
        name: Task Management System

    datasource:
        url: jdbc:h2:mem:taskdb
        driver-class-name: org.h2.Driver
        username: sa
        password: password

    jpa:
        hibernate:
            ddl-auto: update

    h2:
        console:
            enabled: true

    security:
        user:
            name: admin
            password: admin
